#!/bin/bash

# options=(
# 	style=round
# 	width=6.0
# 	active_color=0xc0e2e2e3
# 	inactive_color=0xc02c2e34
# 	background_color=0x302c2e34
# )

options=(
	style=round
	width=8.0
	active_color=0xc000ff80
	inactive_color=0xc02c2e34
	background_color=0x302c2e34
)


borders "${options[@]}"
